lidar_topic: /localisation/lidar/points_legal
imu_topic: /imu/data_raw
odom_topic: /localisation/lidar/odometry
odom_frame: odom
base_frame: base_footprint
invert_odom_tf: false
publish_local_map: false
publish_deskewed_scan: false
deskew: true
voxel_size: 0.20
max_points_per_voxel: 20
min_range: 0.15
max_range: 12.0
max_correspondance_distance: 0.5
convergence_criterion: 0.00001
max_num_threads: 0
initialization_phase: true
max_iterations: 100
double_downsample: true
